// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwemkoYQVXy-GL76BKSRhJ2fQWftxqOuY',
    appId: '1:1052794819571:web:bd5f32ce5df843936ef886',
    messagingSenderId: '1052794819571',
    projectId: 'emart-dd317',
    authDomain: 'emart-dd317.firebaseapp.com',
    storageBucket: 'emart-dd317.appspot.com',
    measurementId: 'G-LE7GHFGM3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyggY4E1b399Dsj2c2_1Vkn2cGkA7IGAE',
    appId: '1:1052794819571:android:b3def259c9b664336ef886',
    messagingSenderId: '1052794819571',
    projectId: 'emart-dd317',
    storageBucket: 'emart-dd317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF3Bqo4Qr1NegBaAkGXNESYTNKZ2Ovbs0',
    appId: '1:1052794819571:ios:d870725ecbf5e71d6ef886',
    messagingSenderId: '1052794819571',
    projectId: 'emart-dd317',
    storageBucket: 'emart-dd317.appspot.com',
    iosBundleId: 'com.example.Ecommerce.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF3Bqo4Qr1NegBaAkGXNESYTNKZ2Ovbs0',
    appId: '1:1052794819571:ios:d7a60ca4e9f493fc6ef886',
    messagingSenderId: '1052794819571',
    projectId: 'emart-dd317',
    storageBucket: 'emart-dd317.appspot.com',
    iosBundleId: 'com.example.Ecommerce.ecommerce.RunnerTests',
  );
}
